spring.application.name=security-service

server.port=8081

jwt.secret=${JWT_SECRET}
jwt.expiration-token=86400000
jwt.expiration-refresh-token=604800000

logging.level.root=INFO
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=INFO